version: '3'
services:
  api-server:
    container_name: api-server
    image: amazoncorretto:8u202
    volumes:
      - ${PWD}:/api-server
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
    environment:
      JAVA_HOME: /usr/lib/jvm/java
    working_dir: /api-server
    command: ./mvnw spring-boot:run
